# Generated by Django 5.2.16 on 2026-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('study_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('school_class', 'subject', 'chapter_number'), name='unique_chapter_number_per_subject'),
        ),
    ]
