# Generated by Django 5.2.16 on 2026-07-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_address_teacher_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
