# Generated by Django 5.2.16 on 2026-08-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admission_student_email_admission_student_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='Address_line1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='Address_line2',
            new_name='address_line2',
        ),
    ]
