# Generated by Django 5.2.16 on 2026-08-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_rename_address_line1_admission_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='student_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
