# Generated by Django 5.2.16 on 2026-07-10 08:34

import admissions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(blank=True, default=admissions.models.generate_application_no, max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('academic_year', models.CharField(max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(max_length=50)),
                ('father_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Address_line1', models.CharField(max_length=100)),
                ('Address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='birth_certificates/')),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='transfer_certificates/')),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='marksheets/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('applying_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
            ],
        ),
    ]
