# Generated by Django 5.2.16 on 2026-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='student_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
