# Generated by Django 5.2.16 on 2026-08-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
