# Generated by Django 5.2.16 on 2026-07-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Experience in years'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(default='unknown', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(default='unknown', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
