# Generated by Django 5.2.16 on 2026-07-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='status',
        ),
    ]
